# Generated by Django 6.0.4 on 2026-04-21 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='rag_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'verbose_name': 'Pedaço de Documento',
                'verbose_name_plural': 'Pedaços de Documentos',
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
