# Generated by Django 6.0.4 on 2026-05-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='solides', help_text='Nome do provedor do webhook', max_length=100)),
                ('endpoint', models.CharField(help_text='URL do endpoint acessado', max_length=255)),
                ('payload_received', models.TextField(blank=True, help_text='JSON bruto recebido na requisição', null=True)),
                ('status_code', models.IntegerField(blank=True, help_text='Status HTTP retornado pelo Crivopy', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o log foi gerado')),
            ],
            options={
                'verbose_name': 'Log de Integração',
                'verbose_name_plural': 'Logs de Integrações',
                'ordering': ['-created_at'],
            },
        ),
    ]
