# Generated by Django 6.0.4 on 2026-05-19 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_job_callback_url_job_external_id_job_external_source'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationlog',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='integrationlog',
            name='payload_received',
        ),
        migrations.RemoveField(
            model_name='integrationlog',
            name='provider',
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='direction',
            field=models.CharField(default='INBOUND', help_text='Direção do fluxo: INBOUND (recebido) ou OUTBOUND (enviado)', max_length=20),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Mensagem descritiva de sucesso ou erro', null=True),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='external_source',
            field=models.CharField(default='solides', help_text='Nome do provedor externo (ex: solides)', max_length=100),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Vaga associada à integração, se aplicável', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.job'),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='payload',
            field=models.JSONField(blank=True, help_text='JSON bruto da requisição/resposta', null=True),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='success',
            field=models.BooleanField(default=True, help_text='Indica se a integração ocorreu com sucesso'),
        ),
    ]
