# Generated by Django 6.0.4 on 2026-05-01 18:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
