# Generated by Django 6.0.4 on 2026-05-01 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_job_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
