# Generated by Django 6.0.4 on 2026-05-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_alter_job_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='callback_url',
            field=models.URLField(blank=True, help_text='URL do sistema que receberá as notas e resumos da IA', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID desta vaga no sistema externo (ex: ID da Sólides)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='external_source',
            field=models.CharField(blank=True, help_text='Nome do sistema de origem (ex: solides)', max_length=100, null=True),
        ),
    ]
